version: "3.8"

services:
  executor:
    build:
      context: .
      args:
        VARIANT: "3.11-bullseye"
        POETRY_EVERSION: "1.8.3"
    hostname: "executor"
    volumes:
      - .:/app
      - ${HOME}/.ssh:/home/vscode/.ssh
    environment:
      PYTHONPATH: /app
    env_file: .env
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        .devcontainer/postCreate.sh
        sleep infinity
    restart: always
    privileged: true
    ipc: host
    tty: true
    depends_on:
      - langserve

  langserve:
    build:
      context: .
      args:
        VARIANT: "3.11-bullseye"
        POETRY_EVERSION: "1.8.3"
    hostname: "langserve"
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - .:/app
      - ${HOME}/.ssh:/home/vscode/.ssh
    environment:
      PYTHONPATH: /app
    env_file: .env
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        .devcontainer/postCreate.sh
        scripts/1_1_serve.sh
    restart: always
    privileged: true
    ipc: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
