services:
  inflo-data:
    image: inflo-ai/inflo-data:0.1.1
    build:
      context: ../inflo-data
      dockerfile: ../inflo-data/docker/Dockerfile
      args:
        ENV: dev
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: inflo-data
    hostname: inflo-data
    restart: always
    volumes:
      - ../inflo-data/logs:/app/logs

networks:
  default:
    name: inflo-network
    external: true
