api:
  port: 8000
  workers: 1

inference:
  llm:
    providers:
      # https://platform.openai.com/docs/models
      openai_nano:
        model_config:
          # model: gpt-4o-mini   # $0.15 / $0.60
          # model: gpt-4.1-nano  # $0.10 / $0.40
          # model: gpt-4.1-mini # $0.40 / $1.60
          # model: gpt-4.1       # $2.00 / $8.00
          model: gpt-5-nano # $0.05 / $0.40
          # model: gpt-5-mini    # $0.25 / $2.00
          # model: gpt-5         # $1.25 / $10.00
          temperature: 0
          max_tokens: 8192
          n: 1
        max_concurrency: 16

      openai_mini:
        model_config:
          # model: gpt-4o-mini   # $0.15 / $0.60
          # model: gpt-4.1-nano  # $0.10 / $0.40
          # model: gpt-4.1-mini # $0.40 / $1.60
          # model: gpt-4.1       # $2.00 / $8.00
          # model: gpt-5-nano    # $0.05 / $0.40
          model: gpt-5-mini # $0.25 / $2.00
          # model: gpt-5         # $1.25 / $10.00
          temperature: 0
          max_tokens: 8192
          n: 1
        max_concurrency: 16

      openai:
        model_config:
          # model: gpt-4o-mini   # $0.15 / $0.60
          # model: gpt-4.1-nano  # $0.10 / $0.40
          # model: gpt-4.1-mini # $0.40 / $1.60
          # model: gpt-4.1       # $2.00 / $8.00
          # model: gpt-5-nano    # $0.05 / $0.40
          # model: gpt-5-mini    # $0.25 / $2.00
          model: gpt-5 # $1.25 / $10.00
          temperature: 0
          max_tokens: 8192
          n: 1
        max_concurrency: 16

      tpu:
        model_config:
          openai_api_base: http://DEV_IP:8000/v1
          model: qwen3-14b
          temperature: 0.7
          top_p: 1.0
          max_tokens: 8192
          presence_penalty: 1.5
          n: 1
          extra_body:
            top_k: -1
            chat_template_kwargs:
              enable_thinking: false
        max_concurrency: 16

  embeddings:
    provider: local
    providers:
      local:
        model_config:
          openai_api_base: http://DEV_IP:8000/v1
          model: dragonkue/snowflake-arctic-embed-l-v2.0-ko
        dimensions: 1024
